Add Embed component to handle iframing V2 tools
berkeley-gif/caladapt-website-2021 pull request #86
Opened 2021-10-14 21:08 UTC by elehmer

This adds a partial component Embed that creates iframe component to handle Cal-Adapt V2 tools. Adds one example for the streamflow tool.

2021-10-14 23:20 UTC, clhenrick requested changes
@elehmer thanks for submitting this! Let me know if you can get the dynamic height solution working mentioned below. Happy to help / pair on it.

2021-10-14 23:20 UTC, clhenrick commented on src/routes/tools/streamflow/index.svelte
>    import { InlineNotification } from "carbon-components-svelte";
@elehmer you can remove this import as it's no longer needed

2021-10-14 23:20 UTC, clhenrick commented on src/routes/tools/streamflow/index.svelte
> +  .iframe-container {
@elehmer I think it would be better if we could set the height to the actual height of the content in the iframe so that it doesn't scroll vertically. [See this SO answer](https://stackoverflow.com/a/9163087) for one way of doing it. 

To get a reference to the `<iframe>` element you'll need to use Svelte's method of element binding. More [in the Svelte docs](https://svelte.dev/docs#bind_element).

2021-10-14 23:49 UTC, clhenrick commented on src/partials/Embed.svelte
> +  .iframe {
p.s. @elehmer with Svelte you don't need to rely on classes when styling a component unless there are multiple instances of the same element. You can just do `iframe { ... }` and Svelte will scope the CSS to this component only.

2021-10-15 00:07 UTC, clhenrick commented
> @elehmer thanks for submitting this! Let me know if you can get the dynamic height solution working mentioned below. Happy to help / pair on it.

Although now I'm realizing that this will not work on cross-origin domains, so it might be hard to get working locally. You might need to write the code locally and then deploy to our server at a different subdomain like `test.cal-adapt.org` to test it.

2021-10-15 18:18 UTC, elehmer commented
I'm either running into cross-origin domain at the window level or it is reporting the wrong height for scrollHeight (probably because the iframe is loading async and is dynamically generated from code). I can't quite remember when cross-origin crops up. Won't we run into the cross-origin issue on the C-A server as well or will it be ok since the cal-adapt.org portion is the same?

I've tried using the onMount on both the Embed.svelte and index.svelte for the tool with the same results. I can set it to a fixed const and it works but if set too high the content is stretched in the iframe. Combining the fixed height with overflow hidden almost completely disables the scroll with just a slight scroll that isn't very noticeable.

Do we have a place to test the cross-origin issue and see if we can get the right value back?

Also, is there an event we can use that runs later then onMount that might return the right value?

2021-10-15 18:32 UTC, mukhtyar commented
@elehmer Let's add a script to the iframed versions of the tools that calculates the body height after rendering and use `postMessage` to communicate it to the iframe. Hopefully that should work with local testing. Otherwise we will have to set up another subdomain to test it.

2021-10-15 20:01 UTC, clhenrick commented
> @elehmer Let's add a script to the iframed versions of the tools that calculates the body height after rendering and use `postMessage` to communicate it to the iframe. Hopefully that should work with local testing. Otherwise we will have to set up another subdomain to test it.

@elehmer @mukhtyar maybe the easiest way to do it would be to add a resize event listener to the iframed page and have it call `postMessage` when it fires.

2021-10-15 20:02 UTC, elehmer commented
I have a working version now using the `postMessage` passing. Working out some annoying binding issues...

2021-10-15 20:40 UTC, elehmer commented
The iframe resizes for the streamflow tool using `postMessage`. Let me know if you see the same behavior I did. If so, I can modify the other v2 iframes to use the `postMessage`.

2021-10-15 20:55 UTC, clhenrick commented
thanks @elehmer I'll take another look

2021-10-15 21:54 UTC, mukhtyar commented
@elehmer it looks good to me. Tried it in a few browsers on a laptop and desktop.

2021-10-15 23:01 UTC, clhenrick reviewed
@elehmer minor suggestions in addition to the solution we discovered of using `scrolling=no` on the `iframe` element.

2021-10-15 23:01 UTC, clhenrick commented on src/partials/Embed.svelte
> +        v2_frame.style.height = `${e.data.height}px`;
it might be good to do a check in an `if` statement here to make sure `e.data.height` exists, and if not emit a `console.warn`

2021-10-15 23:01 UTC, clhenrick commented on src/partials/Embed.svelte
> +</iframe>
also @elehmer just FYI a minor style thing in Svelte: if an element has no children then you can self close it like:

```svelte
<iframe
  src="{src}"
  title="{title}"
  frameborder="0"
  allow="fullscreen"
  bind:this="{v2_frame}"
/>
```

2021-10-15 23:01 UTC, clhenrick commented on src/routes/tools/streamflow/index.svelte
> +<div>
@elehmer I don't think you need this `<div>` element here.

2021-10-15 23:01 UTC, clhenrick commented on src/partials/Embed.svelte
> +</iframe>
For accessibility we should add a `title` attribute with a description of the embed. We could pass that in as a prop from the `tooname/index.svelte` parent.

2021-10-15 23:16 UTC, elehmer commented on src/partials/Embed.svelte
> +</iframe>
Oh weird I had the iframe self closing but then fiddled with it in Sublime Text and it changed it lol. I'll fix that one.

2021-10-15 23:32 UTC, clhenrick commented on src/partials/Embed.svelte
> +</iframe>
No worries. There might be a Svelte plugin or something for Sublime Text. Also I realized you already had a title attribute, my bad.

2021-10-15 23:57 UTC, elehmer commented
Fixed the slight scrolling of iframe by adding `overflow-y: hidden` to the body of the v2 embedded html. Added error handling of `postMessage` data and cleaned up unneeded code. This should now be functional and can be applied to rest of the tools.

2021-10-16 00:49 UTC, clhenrick commented on src/partials/Embed.svelte
> +      if (typeof e.data.height !== "number")
@elehmer I don't think there's a need for using `return` here. You can simplify this / make it a little more readable by making it an `if / else` statement. I might do the check like `if (e.data.height && typeof e.data.height === "number") { ... } else { ... }` in case `height` might not be there and lead with the truthy statement as it's generally easier to follow when something is truthy then fall back to falsey IMO.

2021-10-18 17:02 UTC, clhenrick approved these changes

2021-10-18 17:02 UTC, merged